import {test} from 'node:test';import assert from 'node:assert/strict';
import {mkdtempSync,mkdirSync,writeFileSync,rmSync,readFileSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';import {generateKeyPairSync,sign} from 'node:crypto';
import {loadApprovedGlossary,GLOSSARY_PATH} from './glossary-approval.mjs';
import {staticDocument,proofMessage,STATIC_PROOF_VERSION} from './lib/static-editorial-proof.mjs';
function fixture(fn){
 const root=mkdtempSync(join(tmpdir(),'pag-factual-test-'));const keys=generateKeyPairSync('ed25519');
 const data={title:'Synthetic glossary',description:'Fictional test',heading:'Synthetic glossary',introduction:'Fixture only',terms:[{term:'Example',def:'Synthetic test definition',source:'https://example.com'}]};
 const file=join(root,'src/content/editorial/glossary.json');const receiptPath=join(root,'ops/editorial/approvals/glossary.json');
 mkdirSync(join(root,'src/content/editorial'),{recursive:true});mkdirSync(join(root,'ops/editorial/approvals'),{recursive:true});
 writeFileSync(join(root,'ops/editorial/static-editorial-public-key.pem'),keys.publicKey.export({type:'spki',format:'pem'}));
 function approve(value=data,overrides={}){const raw=JSON.stringify(value,null,2)+'\n';writeFileSync(file,raw);const proof={version:STATIC_PROOF_VERSION,repository:'acwokas/promptandgo',path:GLOSSARY_PATH,document_sha256:staticDocument(raw,GLOSSARY_PATH).sha256,review_sha256:'a'.repeat(64),source_sha256:'b'.repeat(64),reviewed_at:'2026-09-28T00:00:00Z',expires_at:'2026-10-05T00:00:00Z',...overrides};writeFileSync(receiptPath,JSON.stringify({proof,signature:sign(null,Buffer.from(proofMessage(proof)),keys.privateKey).toString('base64')}));}
 const opts={root,now:new Date('2026-09-29T00:00:00Z')};try{fn({data,file,receiptPath,approve,opts});}finally{rmSync(root,{recursive:true,force:true});}
}
test('exact signed complete glossary renders and absent proof holds',()=>fixture(({data,approve,opts,receiptPath})=>{approve();assert.deepEqual(loadApprovedGlossary(opts),data);rmSync(receiptPath);assert.throws(()=>loadApprovedGlossary(opts));}));
test('definitions, titles, sources and added terms require fresh approval',()=>fixture(({data,file,approve,opts})=>{for(const mutate of [d=>d.title='Changed',d=>d.terms[0].def='Changed',d=>d.terms[0].source='https://other.example',d=>d.terms.push({term:'New',def:'New',source:'https://example.com'})]){approve();const changed=structuredClone(data);mutate(changed);writeFileSync(file,JSON.stringify(changed,null,2)+'\n');assert.throws(()=>loadApprovedGlossary(opts));}}));
test('expired, different-repository and different-path approvals hold',()=>fixture(({approve,opts})=>{for(const change of [{expires_at:'2026-09-28T12:00:00Z'},{repository:'acwokas/adrian-2026'},{path:'src/content/writing/test.md'}]){approve(undefined,change);assert.throws(()=>loadApprovedGlossary(opts));}}));
test('forged signature and duplicate JSON keys are held',()=>fixture(({approve,file,receiptPath,opts})=>{approve();const receipt=JSON.parse(readFileSync(receiptPath));receipt.signature=Buffer.alloc(64).toString('base64');writeFileSync(receiptPath,JSON.stringify(receipt));assert.throws(()=>loadApprovedGlossary(opts));approve();writeFileSync(file,'{"title":"First","title":"Second"}\n');assert.throws(()=>loadApprovedGlossary(opts));}));
test('even signed malformed or unsourced entries cannot render',()=>fixture(({data,approve,opts})=>{for(const change of [d=>delete d.terms[0].source,d=>d.terms.push({...d.terms[0]}),d=>d.terms[0].source='javascript:alert(1)',d=>d.heading='']){const changed=structuredClone(data);change(changed);approve(changed);assert.throws(()=>loadApprovedGlossary(opts));}}));
test('normal build and direct Astro page both enforce approval',()=>{const pkg=JSON.parse(readFileSync(new URL('../package.json',import.meta.url)));assert.match(pkg.scripts.build,/check-glossary-facts.mjs && astro build/);const page=readFileSync(new URL('../src/pages/glossary.astro',import.meta.url),'utf8');assert.match(page,/const glossary = loadApprovedGlossary\(\)/);assert.match(page,/const terms: GlossaryTerm\[\] = glossary.terms/);assert.doesNotMatch(page,/const terms.*= \[/);});
