-- Tip article: How to Use a System Prompt for Consistent AI Output
-- Generated by scripts/content/build-tip-migration.mjs, passed gateTip() before this file was written.
-- Sources cited in the body:
--   - ChatGPT Custom Instructions (OpenAI Help Center): https://help.openai.com/en/articles/8096356-chatgpt-custom-instructions (accessed 2026-08-27)
--   - Claude Sonnet 4.5 system prompt release notes (Anthropic): https://platform.claude.com/docs/en/release-notes/system-prompts/claude-sonnet-4-5 (accessed 2026-08-27)
--   - Prompting best practices, role prompting (Anthropic): https://platform.claude.com/docs/en/build-with-claude/prompt-engineering/claude-prompting-best-practices (accessed 2026-08-27)
--   - What are projects? (Anthropic Help Center): https://support.claude.com/en/articles/9517075-what-are-projects (accessed 2026-08-27)
--   - Tips for creating custom Gems (Google Gemini Apps Help): https://support.google.com/gemini/answer/15235603 (accessed 2026-08-27)
--
-- Review before applying. This does not run automatically; apply with
-- `supabase db push` once you are satisfied with the content.

INSERT INTO public.articles (
  title,
  slug,
  content,
  synopsis,
  thumbnail_url,
  published_date,
  is_published,
  focus_keyword,
  keyphrases,
  meta_description,
  meta_title
) VALUES (
  'How to Use a System Prompt for Consistent AI Output',
  'how-to-use-system-prompts-for-consistent-ai-output',
  '<p>Ask ChatGPT for a short, upbeat product description in the first message of a chat, and you will probably get one. Ask again forty messages later in the same conversation, after you have pasted in a spreadsheet, argued about pricing, and asked three unrelated questions, and the tone often drifts: longer sentences creep back in, the "upbeat" note fades, formatting changes. This is not you imagining things. A single instruction buried in message one competes for attention with everything that comes after it, and its influence weakens the longer the conversation runs. A system prompt fixes this by giving the model a standing instruction that sits outside the back and forth of the chat and gets re-applied to every reply, not just the first one.</p>

<h2>What a system prompt actually is</h2>
<p>A system prompt (OpenAI calls it "custom instructions," Anthropic calls it "project instructions," Google calls it a "Gem''s" instructions) is a separate instruction channel from the message box. Instead of living inside the conversation as one message among many, it is attached at a level above the chat, so the model treats it as standing context rather than as one more thing you said. Anthropic''s own documentation describes this directly: setting a role or set of rules in the system prompt "focuses Claude''s behavior" for the whole task, and is one of the most reliable ways to steer tone and domain behavior across a session, according to <a href="https://platform.claude.com/docs/en/build-with-claude/prompt-engineering/claude-prompting-best-practices">Anthropic''s prompt engineering documentation</a>.</p>
<p>You can see this in production. Anthropic actually publishes the system prompt that runs behind claude.ai and its mobile apps, and it is a useful reference point for what a real, working system prompt looks like at scale. The <a href="https://platform.claude.com/docs/en/release-notes/system-prompts/claude-sonnet-4-5">release notes for Claude Sonnet 4.5''s system prompt</a> show it organized into clearly named blocks: product information, refusal handling, tone and formatting, user wellbeing, and a knowledge cutoff notice (Claude''s is set to the end of January 2025). Anthropic has revised that same system prompt at least three times in a five month stretch, with dated versions on September 29, 2025, November 19, 2025, and January 18, 2026, each one adjusting specific instructions such as how Claude handles bullet points or what it says about Anthropic''s product lineup. That is the same idea you are applying at a smaller scale: a standing document, not a one off message, that gets tightened over time.</p>

<h2>Why your first message stops working by message forty</h2>
<p>The instinct most people have is to write a good opening message and expect the model to keep following it. That works for two or three exchanges. The trouble is that everything you type after that first message, plus every reply, becomes part of the same growing block of text the model is reading. An instruction from message one has to keep exerting influence over an ever larger pile of more recent, more specific content. In practice, whatever you asked about most recently tends to dominate, and early stylistic instructions ("keep it under 100 words," "always answer as a skeptical editor," "never use bullet points") get diluted or dropped.</p>
<p>A system prompt does not have this problem, because it is not competing for space inside the conversation history the same way. It is reapplied as standing context on every turn, so a rule you set once still holds at message forty the same way it held at message one. That is the entire practical case for using one: it turns "I hope the model remembers" into "the model is told again, every time."</p>

<h2>The four part method: role, constraints, format, tone</h2>
<p>You do not need to be technical to write a good system prompt. Google''s own guidance for building a Gemini Gem lays out almost exactly this structure, recommending you cover persona, task, context, and format so the Gem can "personalize Gemini''s responses," per <a href="https://support.google.com/gemini/answer/15235603">Google''s official tips for creating custom Gems</a>. Adapted slightly, here is a version that works across ChatGPT, Claude, and Gemini alike.</p>
<p><strong>Role.</strong> State who the model is acting as and for what purpose, in one or two sentences. "You are a copy editor for a small accounting firm''s client emails" does more work than "help me write emails," because it gives the model a consistent lens to filter every later request through, rather than reinterpreting the lens each time.</p>
<p><strong>Constraints.</strong> List the hard rules, the things that should never change no matter what is asked in the chat itself. Length limits, banned words or phrases, facts it should not invent, topics it should decline. Write these as short, specific, non negotiable lines rather than a paragraph of general advice, since specific rules survive a long conversation better than vague ones.</p>
<p><strong>Output format.</strong> Say exactly what the response should look like: plain paragraphs or bullet points, a fixed section order, whether to include a subject line, whether to wrap code in a particular language tag. Anthropic''s published system prompt is a good illustration of how granular this can get: it tells Claude, in effect, to default to prose rather than bullet points for reports and explanations, and to reserve lists for when they are genuinely essential, exactly the kind of formatting default a business owner might want fixed for their own use case too.</p>
<p><strong>Tone.</strong> Describe the voice in concrete, comparable terms rather than adjectives alone. "Direct and plain, like a colleague explaining something over coffee, no corporate language, no exclamation marks" is easier for a model to hold onto across a long session than "friendly and professional," which is vague enough to drift in either direction.</p>

<h2>Where to actually put it in each tool</h2>
<p>ChatGPT, Claude, and Gemini all now support a persistent instructions field, but they differ in where you find it and how much room you get. In ChatGPT, go to Settings, then Personalization, then Custom Instructions. OpenAI''s own help center specifies the limit: free and Go plan users can save up to 1,500 characters of custom instructions, while Plus, Pro, Enterprise, Business, and Education users get up to 5,000 characters, according to the <a href="https://help.openai.com/en/articles/8096356-chatgpt-custom-instructions">official ChatGPT Custom Instructions help article</a>. That is roughly 250 to 850 words depending on your plan, plenty for the four part structure above.</p>
<p>In Claude, the equivalent is Project instructions. Create or open a Project, click into its settings, and add your instructions there; every chat started inside that Project inherits them automatically. Anthropic''s help documentation confirms that project instructions apply across every conversation in that Project and can set tone or point of view for the whole workspace, per its <a href="https://support.claude.com/en/articles/9517075-what-are-projects">official Projects help article</a>, and unlike ChatGPT''s fields, Anthropic does not publish a fixed character cap for this box, since it is bounded by the model''s much larger context window instead.</p>
<p>In Gemini, open Gem manager from the side panel, create a new Gem, and fill in its instructions field using the persona, task, context, and format structure Google recommends in the tips article linked above. A Gem''s instructions persist for every chat you start from that Gem, the same way a ChatGPT custom instruction or a Claude Project instruction does.</p>

<h2>A full example you can copy and adapt</h2>
<p>Here is a working system prompt for a small business owner who wants consistent customer support replies. Paste it into any of the three tools and swap the specifics for your own business.</p>
<p><strong>Role:</strong> You are the customer support voice for Maple &amp; Co, a small online homeware store. You write replies to customer emails and chat messages.<br>
<strong>Constraints:</strong> Never promise a refund or replacement without the customer providing an order number. Never invent shipping dates: if you do not know one, say the team will confirm it within one business day. Do not use exclamation marks. Keep every reply under 120 words unless the customer''s issue clearly needs more detail to resolve.<br>
<strong>Output format:</strong> Start with a one sentence acknowledgement of the customer''s issue. Follow with the resolution or next step in one short paragraph. End with a single sentence offering further help, no sign off block, no bullet points unless listing more than two return steps.<br>
<strong>Tone:</strong> Warm but plain spoken, like a helpful shop assistant, not a corporate script. Avoid words like "unfortunately," "valued customer," or "we apologize for any inconvenience."</p>
<p>Test it by opening a fresh chat, pasting in three or four unrelated sample customer messages back to back, and checking whether the fifth reply still matches the first in length, tone, and structure. If it does, the instructions are doing their job. If it drifts, the usual fix is tightening a vague line into something more concrete, for example replacing "keep it brief" with an actual word count.</p>

<h2>A quick checklist before you rely on it</h2>
<p>Before you treat a system prompt as done, check that it covers all four parts (role, constraints, format, tone), that every constraint is written as a specific rule rather than general advice, that you have tested it across several unrelated messages in one session rather than just the first reply, and that you are using the tool''s persistent instructions field (Custom Instructions, Project instructions, or Gem instructions) rather than just writing a strong opening message and hoping it holds. That last habit is the one thing separating a prompt that works for one reply from one that works for the whole session.</p>',
  'Your first message stops working by message forty. Here is how to write a real system prompt, with the role, constraints, format, and tone method and a full copyable example.',
  NULL,
  '2026-08-31T09:00:00Z',
  true,
  'how to write a system prompt',
  ARRAY['ChatGPT custom instructions', 'Claude project instructions', 'Gemini Gem instructions'],
  'Stop relying on your first message: write a system prompt for ChatGPT, Claude, or Gemini using role, constraints, format, and tone, with a copyable example.',
  'Write a System Prompt for Consistent AI Output'
)
ON CONFLICT (slug) DO NOTHING;
