// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sszxxmxqidkpkhlkstgs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNzenh4bXhxaWRrcGtobGtzdGdzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzY1OTAwMDgsImV4cCI6MjA5MjE2NjAwOH0.W8hk9iWryQ3HahjQg0md133uWJN4rqW4ZFpCpZdmt_g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});